-- Seed: 58 curated sources carried over from v2 (config-as-code)
insert into public.sources (name, feed_url, category, weight, is_enabled, region) values
('BBC News','https://feeds.bbci.co.uk/news/world/rss.xml','world',4,true,'GB'),
('Al Jazeera','https://www.aljazeera.com/xml/rss/all.xml','world',3,true,'QA'),
('NYT World','https://rss.nytimes.com/services/xml/rss/nyt/World.xml','world',4,true,'US'),
('Sky News World','https://feeds.skynews.com/feeds/rss/home.xml','world',4,true,'GB'),
('Wall Street Journal','https://feeds.content.dowjones.io/public/rss/RSSWorldNews','world',4,true,'US'),
('TechCrunch','https://techcrunch.com/feed/','tech',5,true,null),
('The Verge','https://www.theverge.com/rss/index.xml','tech',4,true,null),
('Ars Technica','https://feeds.arstechnica.com/arstechnica/index','tech',5,true,null),
('Engadget','https://www.engadget.com/rss.xml','tech',3,true,null),
('404 Media','https://www.404media.co/rss/','tech',4,true,null),
('MIT Technology Review','https://www.technologyreview.com/feed/','tech',4,true,null),
('CoinDesk','https://www.coindesk.com/arc/outboundfeeds/rss/','crypto',4,true,null),
('Cointelegraph','https://cointelegraph.com/rss','crypto',3,true,null),
('Decrypt','https://decrypt.co/feed','crypto',4,true,null),
('CryptoSlate','https://feeds.feedburner.com/cryptoslate','crypto',5,true,null),
('Financial Times','https://www.ft.com/rss/home','business',5,true,'GB'),
('WSJ Markets','https://feeds.content.dowjones.io/public/rss/RSSMarketsMain','business',4,true,null),
('The Economist (Finance & Econ)','https://www.economist.com/finance-and-economics/rss.xml','economics',5,true,null),
('CNBC','https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100003114','business',3,true,'US'),
('Phys.org','https://phys.org/rss-feed/','science',3,true,null),
('ScienceDaily','https://www.sciencedaily.com/rss/top/science.xml','science',3,true,null),
('NASA Breaking News','https://www.nasa.gov/rss/dyn/breaking_news.rss','space',4,true,null),
('ESPN','https://www.espn.com/espn/rss/news','sports',3,true,null),
('Sky Sports','https://www.skysports.com/rss/12040','sports',3,true,null),
('BBC Sport','https://feeds.bbci.co.uk/sport/rss.xml?edition=uk','sports',4,true,'GB'),
('CBS Sports','https://www.cbssports.com/rss/headlines/','sports',3,true,null),
('The Guardian Sport','https://www.theguardian.com/sport/rss','sports',4,true,'GB'),
('Variety','https://variety.com/feed/','entertainment',3,true,null),
('Deadline','https://deadline.com/feed/','entertainment',3,true,null),
('IndieWire','https://www.indiewire.com/feed/','entertainment',3,true,null),
('Rolling Stone (Music News)','https://www.rollingstone.com/music/music-news/feed/','entertainment',3,true,null),
('Billboard','https://www.billboard.com/feed/','entertainment',3,true,null),
('IGN','https://feeds.feedburner.com/ign/all','gaming',3,true,null),
('Polygon','https://www.polygon.com/feed/','entertainment',3,true,null),
('PC Gamer','https://www.pcgamer.com/uk/rss/','gaming',2,true,null),
('GameSpot','https://www.gamespot.com/feeds/mashup/','gaming',3,true,null),
('Rock Paper Shotgun','https://www.rockpapershotgun.com/feed','gaming',4,true,null),
('St. Louis Fed (FRED) Blog','https://fredblog.stlouisfed.org/feed/','economics',3,true,null),
('Google Blog (AI)','https://blog.google/technology/ai/rss/','ai',4,true,null),
('DeepMind','https://blog.google/technology/google-deepmind/rss/','ai',5,true,null),
('Hugging Face Blog','https://huggingface.co/blog/feed.xml','ai',3,true,null),
('One Useful Thing','https://www.oneusefulthing.org/feed','ai',4,true,null),
('AI Snake Oil','https://www.normaltech.ai/feed','ai',4,true,null),
('The Rundown AI','https://rss.beehiiv.com/feeds/2R3C6Bt5wj.xml','ai',3,true,null),
('The Algorithmic Bridge','https://www.thealgorithmicbridge.com/feed','ai',3,true,null),
('Carbon Brief','https://www.carbonbrief.org/feed/','climate',4,true,null),
('NOAA Climate.gov','https://www.climate.gov/feeds/news-features/highlights.rss','climate',3,false,null),
('Utility Dive','https://www.utilitydive.com/feeds/news/','climate',3,true,null),
('Washington Post','https://feeds.washingtonpost.com/rss/world','world',4,false,null),
('New Atlas Science','https://newatlas.com/science/index.rss','science',3,true,null),
('New Atlas Technology','https://newatlas.com/technology/index.rss','tech',3,true,null),
('The Independent','https://www.independent.co.uk/news/world/rss','world',3,true,null),
('Business Insider','https://feeds.businessinsider.com/custom/all','business',4,true,null),
('Nomadic Matt','https://www.nomadicmatt.com/feed/','travel',3,true,null),
('Goats on the Road','https://www.goatsontheroad.com/feed/','travel',3,true,null),
('Atlas Obscura','https://www.atlasobscura.com/feeds/latest','travel',3,true,null),
('EuroGamer','https://www.eurogamer.net/feed/news','gaming',4,true,null),
('Travel World & Tour','https://feeds.feedburner.com/travelandtourworld/home','travel',3,true,null)
on conflict (feed_url) do nothing;
