-- 67 live-tested feeds added 2026-07-04 (autonomous session) — broad coverage for all 14 topics
insert into public.sources (name, feed_url, category, weight, region) values
('Guardian World','https://www.theguardian.com/world/rss','world',4,'GB'),
('France 24','https://www.france24.com/en/rss','world',3,'FR'),
('DW News','https://rss.dw.com/rdf/rss-en-all','world',3,'DE'),
('NPR News','https://feeds.npr.org/1001/rss.xml','world',4,'US'),
('ABC News (AU)','https://www.abc.net.au/news/feed/51120/rss.xml','world',4,'AU'),
('Times of India','https://timesofindia.indiatimes.com/rssfeeds/296589292.cms','world',3,'IN'),
('SCMP','https://www.scmp.com/rss/91/feed','world',3,'HK'),
('The Guardian Business','https://www.theguardian.com/business/rss','business',4,'GB'),
('TechCrunch','https://techcrunch.com/feed/','tech',4,'US'),
('Wired','https://www.wired.com/feed/rss','tech',4,'US'),
('9to5Mac','https://9to5mac.com/feed/','tech',3,'US'),
('MacRumors','https://feeds.macrumors.com/MacRumors-All','tech',3,'US'),
('The Register','https://www.theregister.com/headlines.atom','tech',3,'GB'),
('Hacker News','https://news.ycombinator.com/rss','tech',3,'US'),
('BleepingComputer','https://www.bleepingcomputer.com/feed/','tech',3,'US'),
('Tom''s Hardware','https://www.tomshardware.com/feeds/all','tech',3,'US'),
('MarketWatch','https://feeds.content.dowjones.io/public/rss/mw_topstories','business',4,'US'),
('Fortune','https://fortune.com/feed/','business',3,'US'),
('Forbes Business','https://www.forbes.com/business/feed/','business',3,'US'),
('Economic Times','https://economictimes.indiatimes.com/rssfeedstopstories.cms','business',3,'IN'),
('Business Insider Markets','https://markets.businessinsider.com/rss/news','business',3,'US'),
('FRED Blog','https://fredblog.stlouisfed.org/feed/','economics',3,'US'),
('Marginal Revolution','https://marginalrevolution.com/feed','economics',3,'US'),
('Calculated Risk','https://www.calculatedriskblog.com/feeds/posts/default','economics',3,'US'),
('The Economist Finance','https://www.economist.com/finance-and-economics/rss.xml','economics',5,'GB'),
('TechCrunch AI','https://techcrunch.com/category/artificial-intelligence/feed/','ai',4,'US'),
('MIT News AI','https://news.mit.edu/rss/topic/artificial-intelligence2','ai',4,'US'),
('Simon Willison','https://simonwillison.net/atom/everything/','ai',3,'GB'),
('Import AI','https://importai.substack.com/feed','ai',3,'US'),
('The Gradient','https://thegradient.pub/rss/','ai',3,'US'),
('Marktechpost','https://www.marktechpost.com/feed/','ai',2,'US'),
('Ars Technica AI','https://arstechnica.com/ai/feed/','ai',4,'US'),
('Nature','https://www.nature.com/nature.rss','science',5,'GB'),
('ScienceDaily','https://www.sciencedaily.com/rss/all.xml','science',3,'US'),
('Quanta Magazine','https://api.quantamagazine.org/feed/','science',4,'US'),
('Live Science','https://www.livescience.com/feeds/all','science',3,'US'),
('Scientific American','http://rss.sciam.com/ScientificAmerican-Global','science',4,'US'),
('New Scientist','https://www.newscientist.com/feed/home/','science',4,'GB'),
('Sky Sports','https://www.skysports.com/rss/12040','sports',4,'GB'),
('Guardian Sport','https://www.theguardian.com/sport/rss','sports',4,'GB'),
('The Block','https://www.theblock.co/rss.xml','crypto',4,'US'),
('Bitcoin Magazine','https://bitcoinmagazine.com/feed','crypto',3,'US'),
('Kotaku','https://kotaku.com/rss','gaming',3,'US'),
('GamesIndustry.biz','https://www.gamesindustry.biz/feed','gaming',3,'GB'),
('Nintendo Life','https://www.nintendolife.com/feeds/latest','gaming',3,'GB'),
('Variety','https://variety.com/feed/','entertainment',4,'US'),
('Hollywood Reporter','https://www.hollywoodreporter.com/feed/','entertainment',4,'US'),
('Rolling Stone','https://www.rollingstone.com/feed/','entertainment',3,'US'),
('Pitchfork','https://pitchfork.com/feed/feed-news/rss','entertainment',3,'US'),
('Space.com','https://www.space.com/feeds/all','space',3,'US'),
('SpaceNews','https://spacenews.com/feed/','space',4,'US'),
('ESA','https://www.esa.int/rssfeed/Our_Activities/Space_News','space',4,'EU'),
('Universe Today','https://www.universetoday.com/feed/','space',3,'CA'),
('Grist','https://grist.org/feed/','climate',3,'US'),
('Guardian Environment','https://www.theguardian.com/environment/rss','climate',4,'GB'),
('Yale E360','https://e360.yale.edu/feed.xml','climate',4,'US'),
('STAT News','https://www.statnews.com/feed/','health',4,'US'),
('KFF Health News','https://kffhealthnews.org/feed/','health',3,'US'),
('NYT Health','https://rss.nytimes.com/services/xml/rss/nyt/Health.xml','health',4,'US'),
('Skift','https://skift.com/feed/','travel',4,'US'),
('The Points Guy','https://thepointsguy.com/feed/','travel',3,'US'),
('Condé Nast Traveler','https://www.cntraveler.com/feed/rss','travel',4,'US'),
('NPR Business','https://feeds.npr.org/1006/rss.xml','business',3,'US'),
('BBC Business','https://feeds.bbci.co.uk/news/business/rss.xml','business',4,'GB'),
('BBC Technology','https://feeds.bbci.co.uk/news/technology/rss.xml','tech',4,'GB'),
('BBC Science','https://feeds.bbci.co.uk/news/science_and_environment/rss.xml','science',4,'GB'),
('BBC Health','https://feeds.bbci.co.uk/news/health/rss.xml','health',4,'GB')
on conflict (feed_url) do nothing;
