-- 0036_promote_gn_sources.sql  (STAGED — apply on Tom's explicit go)
-- Promotes publishers discovered via the Google News census (Tom News, 2026-07-12) to
-- first-class RSS feeds so the Google-News hybrid fill can retire. Every feed below was
-- verified to parse with >=3 items. feed_url is UNIQUE so re-runs are idempotent.
-- 471 feeds (216 carry images natively → NewsFirst gets photos without decoding).
insert into public.sources (name, feed_url, home_url, category, weight, region, meta) values
  ('africanews.com', 'https://africanews.com/feed', 'https://africanews.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('AI Business', 'https://aibusiness.com/rss.xml', 'https://aibusiness.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('AI News', 'https://www.artificialintelligence-news.com/feed/', 'https://artificialintelligence-news.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Alliance magazine', 'https://alliancemagazine.org/feed', 'https://alliancemagazine.org', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Benzinga', 'https://benzinga.com/feed', 'https://benzinga.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Biometric Update', 'https://biometricupdate.com/feed', 'https://biometricupdate.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Broadband TV News', 'https://broadbandtvnews.com/feed', 'https://broadbandtvnews.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Bruegel', 'https://bruegel.org/rss.xml', 'https://bruegel.org', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Capitol News Illinois', 'https://capitolnewsillinois.com/feed/', 'https://capitolnewsillinois.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('City Journal', 'https://city-journal.org/rss.xml', 'https://city-journal.org', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Davis Vanguard', 'https://davisvanguard.org/feed/', 'https://davisvanguard.org', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Electronic Frontier Foundation', 'https://eff.org/rss.xml', 'https://eff.org', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('End Violence Against Women', 'https://www.endviolenceagainstwomen.org.uk/feed/', 'https://endviolenceagainstwomen.org.uk', 'ai', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Finance Magnates', 'https://www.financemagnates.com/feed', 'https://financemagnates.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('FIRE | Foundation for Individual Rights and Expression', 'https://fire.org/feed', 'https://fire.org', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Foley & Lardner LLP', 'https://foley.com/feed', 'https://foley.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Globes - Israel Business News', 'https://en.globes.co.il/WebService/Rss/RssFeeder.asmx/FeederNode?iID=942', 'https://en.globes.co.il', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('HTN Health Tech News', 'https://htn.co.uk/feed/', 'https://htn.co.uk', 'ai', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('inc.com', 'https://inc.com/rss', 'https://inc.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('IT Brief UK', 'https://itbrief.co.uk/feed', 'https://itbrief.co.uk', 'ai', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('IT Pro', 'https://www.itpro.com/feeds.xml', 'https://itpro.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Just Security', 'https://www.justsecurity.org/feed/', 'https://justsecurity.org', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Luxembourg Times', 'https://luxtimes.lu/en/rss', 'https://luxtimes.lu', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Manufacturing Chemist', 'https://manufacturingchemist.com/rss', 'https://manufacturingchemist.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('MediaNama', 'https://www.medianama.com/feed/', 'https://medianama.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Memeburn', 'https://memeburn.com/feed', 'https://memeburn.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('MyStateline', 'https://mystateline.com/feed', 'https://mystateline.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('qz.com', 'https://qz.com/feed', 'https://qz.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Reason Magazine', 'https://reason.com/feed/', 'https://reason.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('spyglass.org', 'https://spyglass.org/rss/', 'https://spyglass.org', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('telefonica.com', 'https://telefonica.com/en/rss', 'https://telefonica.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The National Law Review', 'https://natlawreview.com/feed', 'https://natlawreview.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The New Stack', 'https://thenewstack.io/feed', 'https://thenewstack.io', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('the-decoder.com', 'https://the-decoder.com/feed/', 'https://the-decoder.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Today''s Conveyancer', 'https://todaysconveyancer.co.uk/feed/', 'https://todaysconveyancer.co.uk', 'ai', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('WPR', 'https://www.wpr.org/feed', 'https://wpr.org', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('WTTW', 'https://news.wttw.com/feed', 'https://news.wttw.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('airlive', 'https://airlive.net/feed/', 'https://airlive.net', 'business', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Autocar', 'https://www.autocar.co.uk/rss', 'https://autocar.co.uk', 'business', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Derbyshire Times', 'https://www.derbyshiretimes.co.uk/rss', 'https://derbyshiretimes.co.uk', 'business', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "blocked"}'),
  ('Devon Live', 'https://www.devonlive.com/rss.xml', 'https://devonlive.com', 'business', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Amnesty International', 'https://www.amnesty.org/en/feed/', 'https://amnesty.org', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Balkan Green Energy News', 'https://balkangreenenergynews.com/feed/', 'https://balkangreenenergynews.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('BioEnergy Times', 'https://bioenergytimes.com/feed/', 'https://bioenergytimes.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('BloombergNEF', 'https://about.bnef.com/feed', 'https://about.bnef.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Bodyshop Magazine', 'https://www.bodyshopmag.com/feed/', 'https://bodyshopmag.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Brighton & Hove City Council', 'https://brighton-hove.gov.uk/rss.xml', 'https://brighton-hove.gov.uk', 'climate', 4, 'gb', '{"origin": "gn_census", "authority": 0.8, "verify": "unknown"}'),
  ('Canary Media', 'https://www.canarymedia.com/rss.rss', 'https://canarymedia.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('CarNewsChina.com', 'https://carnewschina.com/feed', 'https://carnewschina.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('CleanTechnica', 'https://cleantechnica.com/feed/', 'https://cleantechnica.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Climate Home News', 'https://climatechangenews.com/feed', 'https://climatechangenews.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Climate KIC', 'https://climate-kic.org/feed', 'https://climate-kic.org', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Council on Foreign Relations', 'https://cfr.org/feed', 'https://cfr.org', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Dailynewsegypt', 'https://www.dailynewsegypt.com/feed/', 'https://dailynewsegypt.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('driving.ca', 'https://driving.ca/feed', 'https://driving.ca', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('E3G', 'https://e3g.org/feed', 'https://e3g.org', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('East Devon District Council', 'https://news.eastdevon.gov.uk/rss', 'https://news.eastdevon.gov.uk', 'climate', 4, 'gb', '{"origin": "gn_census", "authority": 0.8, "verify": "unknown"}'),
  ('ecoportal.net', 'https://www.ecoportal.net/feed/', 'https://ecoportal.net', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Egyptian Gazette', 'https://egyptian-gazette.com/feed', 'https://egyptian-gazette.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Electric Cars Report', 'https://electriccarsreport.com/feed/', 'https://electriccarsreport.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('electrive.com', 'https://electrive.com/feed', 'https://electrive.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Energetica India Magazine', 'https://energetica-india.net/rss.xml', 'https://energetica-india.net', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('EnviroNews Nigeria', 'https://www.environewsnigeria.com/feed/', 'https://environewsnigeria.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('EV Powered', 'https://evpowered.co.uk/feed/', 'https://evpowered.co.uk', 'climate', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Fuel Cells Works', 'https://fuelcellsworks.com/feed', 'https://fuelcellsworks.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Global Government Forum', 'https://www.globalgovernmentforum.com/feed/', 'https://globalgovernmentforum.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('GMK Center', 'https://gmk.center/feed', 'https://gmk.center', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('InsideEVs', 'https://insideevs.com/rss/news/all/', 'https://insideevs.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Interesting Engineering', 'https://interestingengineering.com/feed', 'https://interestingengineering.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Irish Examiner', 'https://www.irishexaminer.com/feed/35-top_news.xml', 'https://irishexaminer.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Jalopnik', 'https://www.jalopnik.com/category/news/feed/', 'https://jalopnik.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('MarketScale', 'https://www.marketscale.com/news/rss.xml', 'https://marketscale.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('My Edmonds News', 'https://myedmondsnews.com/feed/', 'https://myedmondsnews.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('New Civil Engineer', 'https://www.newcivilengineer.com/feed/', 'https://newcivilengineer.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Noema Magazine', 'https://www.noemamag.com/feed/', 'https://noemamag.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('North West Londoner', 'https://nwlondoner.co.uk/feed', 'https://nwlondoner.co.uk', 'climate', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('NorthernSound', 'https://northernsound.ie/feed', 'https://northernsound.ie', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('OkDiario', 'https://okdiario.com/feed', 'https://okdiario.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Pacific Islands Forum Secretariat', 'https://forumsec.org/rss.xml', 'https://forumsec.org', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Peterborough Telegraph', 'https://peterboroughtoday.co.uk/rss', 'https://peterboroughtoday.co.uk', 'climate', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('POWER Magazine', 'https://powermag.com/feed', 'https://powermag.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('RaleighNC.gov', 'https://raleighnc.gov/rss.xml', 'https://raleighnc.gov', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('SMMT', 'https://smmt.co.uk/feed', 'https://smmt.co.uk', 'climate', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Tehran Times', 'https://tehrantimes.com/rss', 'https://tehrantimes.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Cool Down', 'https://www.thecooldown.com/feed/', 'https://thecooldown.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Daily Star', 'https://thedailystar.net/rss.xml', 'https://thedailystar.net', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Diplomat – Asia-Pacific', 'https://thediplomat.com/feed', 'https://thediplomat.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Japan Times', 'https://japantimes.co.jp/feed/', 'https://japantimes.co.jp', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Seattle Times', 'https://www.seattletimes.com/feed/', 'https://seattletimes.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('theenergyst.com', 'https://theenergyst.com/feed/', 'https://theenergyst.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Time Magazine', 'https://time.com/feed', 'https://time.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('UNEP Finance Initiative', 'https://www.unepfi.org/feed/', 'https://unepfi.org', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('University of Exeter News', 'https://news.exeter.ac.uk/feed/', 'https://news.exeter.ac.uk', 'climate', 4, 'gb', '{"origin": "gn_census", "authority": 0.82, "verify": "unknown"}'),
  ('volkswagen-group.com', 'https://volkswagen-group.com/en/feeds/press-releases', 'https://volkswagen-group.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('AMBCrypto', 'https://ambcrypto.com/feed/', 'https://ambcrypto.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('BeInCrypto', 'https://beincrypto.com/feed', 'https://beincrypto.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('CoinGecko', 'https://coingecko.com/feed', 'https://coingecko.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Cointribune', 'https://www.cointribune.com/feed/', 'https://cointribune.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Cryptonews.net', 'https://cryptonews.net/rss.xml', 'https://cryptonews.net', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('CryptoPotato', 'https://cryptopotato.com/feed/', 'https://cryptopotato.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('CryptoSlate', 'https://cryptoslate.com/feed/', 'https://cryptoslate.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Deccan Herald', 'https://deccanherald.com/feed', 'https://deccanherald.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Diari ARA', 'https://en.ara.cat/rss/', 'https://en.ara.cat', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Dow Jones', 'https://www.dowjones.com/feed/', 'https://dowjones.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('ETF Database', 'https://etfdb.com/feed/', 'https://etfdb.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('finchannel', 'https://finchannel.com/feed/', 'https://finchannel.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('FX News Group', 'https://fxnewsgroup.com/feed/', 'https://fxnewsgroup.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('FXStreet', 'https://fxstreet.com/rss', 'https://fxstreet.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Global Initiative against Transnational Organized Crime (GI-TOC)', 'https://globalinitiative.net/feed', 'https://globalinitiative.net', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('International Adviser', 'https://www.international-adviser.com/feed/', 'https://international-adviser.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('International Consortium of Investigative Journalists - ICIJ', 'https://icij.org/feed', 'https://icij.org', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Investing News Network', 'https://investingnews.com/feed', 'https://investingnews.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('JournalArta', 'https://journalarta.com/feed/', 'https://journalarta.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Kavout | AI', 'https://kavout.com/rss.xml', 'https://kavout.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('kuathletics.com', 'https://kuathletics.com/rss', 'https://kuathletics.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Mishcon de Reya LLP', 'https://mishcon.com/rss', 'https://mishcon.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Muslim Network TV', 'https://www.muslimnetwork.tv/feed/', 'https://muslimnetwork.tv', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Royal United Services Institute (RUSI)', 'https://rusi.org/rss/latest-commentary.xml', 'https://rusi.org', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('santander.com', 'https://www.santander.com/content/santander-corporate/san-global/en/stories.sitefeed.rss.xml', 'https://santander.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Tekedia', 'https://www.tekedia.com/feed/', 'https://tekedia.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Coin Republic', 'https://www.thecoinrepublic.com/feed/', 'https://thecoinrepublic.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Cryptonomist', 'https://en.cryptonomist.ch/feed/', 'https://en.cryptonomist.ch', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Daily Upside', 'https://www.thedailyupside.com/feed/', 'https://thedailyupside.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Texas Tribune', 'https://www.texastribune.org/feed/', 'https://texastribune.org', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('صوت الإمارات', 'https://voiceofemirates.com/feed', 'https://voiceofemirates.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('93.3 The Drive', 'https://933thedrive.com/feed', 'https://933thedrive.com', 'economics', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('AHDB', 'https://ahdb.org.uk/rss', 'https://ahdb.org.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('BE News', 'https://benews.co.uk/feed/', 'https://benews.co.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Big Issue', 'https://www.bigissue.com/feed/', 'https://bigissue.com', 'economics', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Building Design', 'https://www.bdonline.co.uk/6148.rss', 'https://bdonline.co.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('CEPR', 'https://cepr.org/rss.xml', 'https://cepr.org', 'economics', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('City AM', 'https://www.cityam.com/feed/', 'https://cityam.com', 'economics', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Contractor UK', 'https://contractoruk.com/rss.xml', 'https://contractoruk.com', 'economics', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Estate Agent Today', 'https://estateagenttoday.co.uk/rss', 'https://estateagenttoday.co.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Food Foundation', 'https://foodfoundation.org.uk/rss.xml', 'https://foodfoundation.org.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Geographical', 'https://geographical.co.uk/feed', 'https://geographical.co.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Housing Digital', 'https://housingdigital.co.uk/feed/', 'https://housingdigital.co.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('ING THINK economic and financial analysis | ING THINK', 'https://think.ing.com/rss', 'https://think.ing.com', 'economics', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Landlord Today', 'https://landlordtoday.co.uk/rss', 'https://landlordtoday.co.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Letting Agent Today', 'https://lettingagenttoday.co.uk/rss', 'https://lettingagenttoday.co.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('London Business News', 'https://londonlovesbusiness.com/feed/', 'https://londonlovesbusiness.com', 'economics', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Mortgage Finance Gazette –', 'https://www.mortgagefinancegazette.com/feed/', 'https://mortgagefinancegazette.com', 'economics', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Mortgage Soup', 'https://mortgagesoup.co.uk/feed/', 'https://mortgagesoup.co.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Mortgage Strategy', 'https://www.mortgagestrategy.co.uk/feed/', 'https://mortgagestrategy.co.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('North Edinburgh News', 'https://nen.press/feed/', 'https://nen.press', 'economics', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Pegasus Group', 'https://www.pegasusgroup.co.uk/feed/', 'https://pegasusgroup.co.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Planning, Building & Construction Today', 'https://www.pbctoday.co.uk/news/feed/', 'https://pbctoday.co.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Portfolio Adviser', 'https://portfolio-adviser.com/feed/', 'https://portfolio-adviser.com', 'economics', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Premier Construction News', 'https://premierconstructionnews.com/feed/', 'https://premierconstructionnews.com', 'economics', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Property Industry Eye', 'https://propertyindustryeye.com/feed', 'https://propertyindustryeye.com', 'economics', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Property Investor Today', 'https://www.propertyinvestortoday.co.uk/feed/', 'https://propertyinvestortoday.co.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('PropertyWire', 'https://www.propertywire.com/feed/', 'https://propertywire.com', 'economics', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('South West Londoner', 'https://swlondoner.co.uk/feed', 'https://swlondoner.co.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('St. James’s Place', 'https://sjp.co.uk/rss.xml', 'https://sjp.co.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Armchair Trader', 'https://www.thearmchairtrader.com/feed/', 'https://thearmchairtrader.com', 'economics', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Business Times', 'https://businesstimes.com.sg/rss.xml', 'https://businesstimes.com.sg', 'economics', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Critic', 'https://thecritic.co.uk/feed/', 'https://thecritic.co.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Intermediary', 'https://theintermediary.co.uk/feed/', 'https://theintermediary.co.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Thelead.uk', 'https://national.thelead.uk/feed', 'https://national.thelead.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('thenegotiator.co.uk', 'https://thenegotiator.co.uk/feed/', 'https://thenegotiator.co.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('thenewworld.co.uk', 'https://thenewworld.co.uk/feed', 'https://thenewworld.co.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('what MORTGAGE', 'https://www.whatmortgage.co.uk/feed/', 'https://whatmortgage.co.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Women''s Budget Group', 'https://wbg.org.uk/feed', 'https://wbg.org.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('YouGov', 'https://yougov.com/en/rss', 'https://yougov.com', 'economics', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('A.V. Club', 'https://www.avclub.com/rss.xml', 'https://avclub.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('ABC7 Los Angeles', 'https://abc7.com/feed/', 'https://abc7.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Bell of Lost Souls', 'https://www.belloflostsouls.net/feed', 'https://belloflostsouls.net', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Cosmopolitan', 'https://cosmopolitan.com/rss', 'https://cosmopolitan.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Discover SWNS', 'https://discover.swns.com/feed', 'https://discover.swns.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('E! News', 'https://eonline.com/feed', 'https://eonline.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('empireonline.com', 'https://rss.onebauer.media/api/feed-aggregator?hostname=https://www.empireonline.com', 'https://empireonline.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Far Out Magazine', 'https://faroutmagazine.co.uk/feed/', 'https://faroutmagazine.co.uk', 'entertainment', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "blocked"}'),
  ('Fox News', 'https://moxie.foxnews.com/google-publisher/latest.xml', 'https://foxnews.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('jezebel.com', 'https://www.jezebel.com/rss.xml', 'https://jezebel.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Literary Hub', 'https://lithub.com/home-page-rigel-two-up-2/feed/', 'https://lithub.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Louder', 'https://www.loudersound.com/feeds.xml', 'https://loudersound.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Marie Claire', 'https://www.marieclaire.com/feeds.xml', 'https://marieclaire.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('MovieWeb', 'https://movieweb.com/feed', 'https://movieweb.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Music-News.com', 'https://music-news.com/rss/c5RAS2tkYoRTvbRq/competitions', 'https://music-news.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('MusicRadar', 'https://www.musicradar.com/feeds.xml', 'https://musicradar.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Neuroscience News', 'https://neurosciencenews.com/feed/', 'https://neurosciencenews.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('NME', 'https://www.nme.com/feed', 'https://nme.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('North Wales Live', 'https://www.dailypost.co.uk/rss.xml', 'https://dailypost.co.uk', 'entertainment', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Northeast Times', 'https://northeasttimes.com/feed/', 'https://northeasttimes.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Page Six', 'https://pagesix.com/feed/', 'https://pagesix.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('PureWow', 'https://www.purewow.com/rss/feed_national.xml', 'https://purewow.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Radio Times', 'https://www.radiotimes.com/feed', 'https://radiotimes.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('The Ankler', 'https://theankler.com/feed/', 'https://theankler.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Free Press', 'https://thefp.com/feed', 'https://thefp.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('TMZ', 'https://www.tmz.com/rss.xml', 'https://tmz.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('upi.com', 'https://rss.upi.com/news/news.rss', 'https://upi.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Vogue', 'https://www.vogue.com/feed/rss', 'https://vogue.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('WWD', 'https://wwd.com/feed/rss/', 'https://wwd.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('YourTango', 'https://www.yourtango.com/rss.xml', 'https://yourtango.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Cambridge News', 'https://www.cambridge-news.co.uk/rss.xml', 'https://cambridge-news.co.uk', 'health', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Cancer Research UK - Cancer News', 'https://news.cancerresearchuk.org/feed/', 'https://news.cancerresearchuk.org', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('CIDRAP', 'https://cidrap.umn.edu/rss.xml', 'https://cidrap.umn.edu', 'health', 4, null, '{"origin": "gn_census", "authority": 0.82, "verify": "unknown"}'),
  ('Community Pharmacy England', 'https://cpe.org.uk/feed/podcast', 'https://cpe.org.uk', 'health', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Corporate Adviser', 'https://corporate-adviser.com/feed/', 'https://corporate-adviser.com', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('GOV.UK blogs', 'https://educationhub.blog.gov.uk/feed/', 'https://educationhub.blog.gov.uk', 'health', 4, 'gb', '{"origin": "gn_census", "authority": 0.8, "verify": "unknown"}'),
  ('Health & Protection', 'https://healthcareandprotection.com/feed/', 'https://healthcareandprotection.com', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('health-ni.gov.uk', 'https://health-ni.gov.uk/rss.xml', 'https://health-ni.gov.uk', 'health', 4, 'gb', '{"origin": "gn_census", "authority": 0.8, "verify": "unknown"}'),
  ('Healthwatch', 'https://healthwatch.co.uk/rss.xml', 'https://healthwatch.co.uk', 'health', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('HSJ | Health Service Journal', 'https://www.hsj.co.uk/20703.rss', 'https://hsj.co.uk', 'health', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('hyphenonline.com', 'https://hyphenonline.com/feed/', 'https://hyphenonline.com', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('IAM Patent', 'https://iam-media.com/rss', 'https://iam-media.com', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('KFF', 'https://www.kff.org/feed/', 'https://kff.org', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Leeds Live', 'https://www.leeds-live.co.uk/rss.xml', 'https://leeds-live.co.uk', 'health', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('LowDownNHS', 'https://lowdownnhs.info/feed/', 'https://lowdownnhs.info', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Medical Xpress', 'https://medicalxpress.com/rss-feed/', 'https://medicalxpress.com', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Nation.Cymru', 'https://nation.cymru/feed/', 'https://nation.cymru', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('National Health Executive', 'https://nationalhealthexecutive.com/rss.xml', 'https://nationalhealthexecutive.com', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Newsroom | Weill Cornell Medicine', 'https://news.weill.cornell.edu/rss.xml', 'https://news.weill.cornell.edu', 'health', 4, null, '{"origin": "gn_census", "authority": 0.82, "verify": "unknown"}'),
  ('Oncodaily', 'https://oncodaily.com/feed', 'https://oncodaily.com', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Pharmacy Business', 'https://pharmacy.biz/feeds/feed.rss', 'https://pharmacy.biz', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Public Sector Executive', 'https://publicsectorexecutive.com/rss.xml', 'https://publicsectorexecutive.com', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Pulse 2.0', 'https://pulse2.com/feed', 'https://pulse2.com', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Research Professional News', 'https://www.researchprofessionalnews.com/feed/', 'https://researchprofessionalnews.com', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('ScienceAlert', 'https://www.sciencealert.com/feed/gn/', 'https://sciencealert.com', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('SciTechDaily', 'https://scitechdaily.com/feed/', 'https://scitechdaily.com', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "blocked"}'),
  ('Shropshire Council Newsroom', 'https://newsroom.shropshire.gov.uk/feed/', 'https://newsroom.shropshire.gov.uk', 'health', 4, 'gb', '{"origin": "gn_census", "authority": 0.8, "verify": "unknown"}'),
  ('Silicon Canals', 'https://siliconcanals.com/feed', 'https://siliconcanals.com', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Socialist Worker', 'https://socialistworker.co.uk/feed/', 'https://socialistworker.co.uk', 'health', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Stock Titan', 'https://www.stocktitan.net/rss', 'https://stocktitan.net', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Swansea Bay University Health Board', 'https://sbuhb.nhs.wales/index.cfm/_api/feed/v1/ABMUhb/?feedID=39B4D864-AFA7-4289-B7064B67D4B0DCEC', 'https://sbuhb.nhs.wales', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Bulwark', 'https://thebulwark.com/feed', 'https://thebulwark.com', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Hill', 'https://thehill.com/feed/', 'https://thehill.com', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Hindu', 'https://www.thehindu.com/feeder/default.rss', 'https://thehindu.com', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Sentinel', 'https://www.stokesentinel.co.uk/rss.xml', 'https://stokesentinel.co.uk', 'health', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The University of Manchester', 'https://manchester.ac.uk/rss', 'https://manchester.ac.uk', 'health', 4, 'gb', '{"origin": "gn_census", "authority": 0.82, "verify": "unknown"}'),
  ('University of Cambridge', 'https://cam.ac.uk/feed', 'https://cam.ac.uk', 'health', 4, 'gb', '{"origin": "gn_census", "authority": 0.82, "verify": "unknown"}'),
  ('University of Liverpool', 'https://news.liverpool.ac.uk/feed/', 'https://news.liverpool.ac.uk', 'health', 4, 'gb', '{"origin": "gn_census", "authority": 0.82, "verify": "unknown"}'),
  ('VaccinesToday', 'https://vaccinestoday.eu/feed', 'https://vaccinestoday.eu', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Wakefield Express', 'https://wakefieldexpress.co.uk/rss', 'https://wakefieldexpress.co.uk', 'health', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('BioPharma Dive', 'https://www.biopharmadive.com/feeds/news/', 'https://biopharmadive.com', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('BioTechniques', 'https://biotechniques.com/feed', 'https://biotechniques.com', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Brownfield Ag News', 'https://www.brownfieldagnews.com/feed/', 'https://brownfieldagnews.com', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Centro Nacional de Investigaciones Oncológicas - CNIO', 'https://www.cnio.es/feed/', 'https://cnio.es', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('CPG Click Oil and Gas', 'https://en.clickpetroleoegas.com.br/feed', 'https://en.clickpetroleoegas.com.br', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Futurism', 'https://futurism.com/feed', 'https://futurism.com', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Genetic Engineering and Biotechnology News', 'https://www.genengnews.com/feed/', 'https://genengnews.com', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Genetic Literacy Project', 'https://geneticliteracyproject.org/feed', 'https://geneticliteracyproject.org', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Inside Precision Medicine', 'https://www.insideprecisionmedicine.com/feed/', 'https://insideprecisionmedicine.com', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Labiotech.eu', 'https://www.labiotech.eu/feed/', 'https://labiotech.eu', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('National Press Foundation', 'https://nationalpress.org/feed/', 'https://nationalpress.org', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('News-Medical', 'https://www.news-medical.net/syndication.axd?format=rss', 'https://news-medical.net', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Press and Journal', 'https://www.pressandjournal.co.uk/feed', 'https://pressandjournal.co.uk', 'science', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('RegMedNet', 'https://regmednet.com/feed', 'https://regmednet.com', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Science Media Centre España', 'https://sciencemediacentre.es/rss.xml', 'https://sciencemediacentre.es', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Scientific American', 'https://www.scientificamerican.com/platform/syndication/rss/', 'https://scientificamerican.com', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('SingularityHub', 'https://singularityhub.com/feed/', 'https://singularityhub.com', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Space Daily', 'https://spacedaily.com/feed', 'https://spacedaily.com', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('The University of Utah', 'https://attheu.utah.edu/feed/', 'https://attheu.utah.edu', 'science', 4, null, '{"origin": "gn_census", "authority": 0.82, "verify": "unknown"}'),
  ('UBC Faculty of Medicine', 'https://med.ubc.ca/feed', 'https://med.ubc.ca', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('UIC today', 'https://today.uic.edu/feed', 'https://today.uic.edu', 'science', 4, null, '{"origin": "gn_census", "authority": 0.82, "verify": "unknown"}'),
  ('Van Andel Institute', 'https://www.vai.org/feed/', 'https://vai.org', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('www.heart.org', 'https://newsroom.heart.org/rss.xml', 'https://newsroom.heart.org', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Межа. Новини України.', 'https://mezha.net/feed', 'https://mezha.net', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Advanced Television', 'https://www.advanced-television.com/feed/', 'https://advanced-television.com', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Aerospace America', 'https://aerospaceamerica.aiaa.org/feed/', 'https://aerospaceamerica.aiaa.org', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Astrobiology Web', 'https://astrobiology.com/feed/', 'https://astrobiology.com', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Astronomy.com', 'https://www.astronomy.com/feed/', 'https://astronomy.com', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Aviation Week', 'https://aviationweek.com/rss.xml', 'https://aviationweek.com', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Breakingthenews.net', 'https://breakingthenews.net/news-feed.xml', 'https://breakingthenews.net', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Carnegie Science', 'https://carnegiescience.edu/rss.xml', 'https://carnegiescience.edu', 'space', 4, null, '{"origin": "gn_census", "authority": 0.82, "verify": "unknown"}'),
  ('Futura, le média qui explore le monde', 'https://www.futura-sciences.com/rss/actualites.xml', 'https://futura-sciences.com', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Inside Outer Space', 'https://www.LeonardDavid.com/feed/', 'https://leonarddavid.com', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('La Brújula Verde', 'https://www.labrujulaverde.com/feed', 'https://labrujulaverde.com', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Modern Diplomacy', 'https://moderndiplomacy.eu/feed', 'https://moderndiplomacy.eu', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('National Air and Space Museum', 'https://airandspace.si.edu/rss.xml', 'https://airandspace.si.edu', 'space', 4, null, '{"origin": "gn_census", "authority": 0.82, "verify": "unknown"}'),
  ('Nautilus | Science', 'https://nautil.us/feed', 'https://nautil.us', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Newswise', 'https://feeds.feedburner.com/NewswiseLatestNews', 'https://newswise.com', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Noticias Ambientales', 'https://noticiasambientales.com/feed/', 'https://noticiasambientales.com', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Pandaily', 'https://pandaily.com/feed', 'https://pandaily.com', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Report.az', 'https://report.az/rss', 'https://report.az', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Sci.News', 'https://sci.news/feed', 'https://sci.news', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Sky & Telescope', 'https://skyandtelescope.org/feed/', 'https://skyandtelescope.org', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('SpaceWatch.GLOBAL', 'https://spacewatch.global/feed/', 'https://spacewatch.global', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Tech Explorist', 'https://www.techexplorist.com/feed/', 'https://techexplorist.com', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Technology Org', 'https://technology.org/feed/', 'https://technology.org', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Teslarati', 'https://www.teslarati.com/feed/', 'https://teslarati.com', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Debrief', 'https://thedebrief.org/feed/', 'https://thedebrief.org', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('University of St Andrews', 'https://news.st-andrews.ac.uk/feed/', 'https://news.st-andrews.ac.uk', 'space', 4, 'gb', '{"origin": "gn_census", "authority": 0.82, "verify": "unknown"}'),
  ('ValleyCentral.com', 'https://valleycentral.com/feed', 'https://valleycentral.com', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Access All Areas', 'https://accessaa.co.uk/feed/', 'https://accessaa.co.uk', 'sports', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Anfield Watch', 'https://anfieldwatch.co.uk/feed', 'https://anfieldwatch.co.uk', 'sports', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Autosport', 'https://www.autosport.com/rss/google/', 'https://autosport.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Betway Insider', 'https://blog.betway.com/feed/', 'https://blog.betway.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('British F4 Championship', 'https://fiaformula4.com/feed', 'https://fiaformula4.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Chronicle Live', 'https://www.chroniclelive.co.uk/rss.xml', 'https://chroniclelive.co.uk', 'sports', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Coventry City Football Club', 'https://ccfc.co.uk/rss.xml', 'https://ccfc.co.uk', 'sports', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Crash.net', 'https://www.crash.net/rss', 'https://crash.net', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('CSIS | Center for Strategic and International Studies', 'https://csis.org/rss.xml', 'https://csis.org', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Daily Star', 'https://www.dailystar.co.uk/rss.xml', 'https://dailystar.co.uk', 'sports', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Derbyshire Live', 'https://www.derbytelegraph.co.uk/rss.xml', 'https://derbytelegraph.co.uk', 'sports', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('FAW', 'https://faw.cymru/feed/', 'https://faw.cymru', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Football Italia', 'https://football-italia.net/feed/', 'https://football-italia.net', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Football365', 'https://football365.com/rss', 'https://football365.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('footballtransfers.com', 'https://footballtransfers.com/feed', 'https://footballtransfers.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Footy Headlines', 'https://www.footyheadlines.com/atom.xml', 'https://footyheadlines.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('FotMob', 'https://www.fotmob.com/topnews/feed?format=atom', 'https://fotmob.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('FourFourTwo', 'https://www.fourfourtwo.com/feeds.xml', 'https://fourfourtwo.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('GlasgowWorld', 'https://glasgowworld.com/rss', 'https://glasgowworld.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('GPblog', 'https://www.gpblog.com/en/sitemap/news.xml', 'https://gpblog.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('grandprix247', 'https://www.grandprix247.com/sitemap/news.xml', 'https://grandprix247.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('House & Garden', 'https://www.houseandgarden.co.uk/feed/rss', 'https://houseandgarden.co.uk', 'sports', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Hull Live', 'https://www.hulldailymail.co.uk/rss.xml', 'https://hulldailymail.co.uk', 'sports', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Motorsport.com', 'https://www.motorsport.com/rss/google/', 'https://motorsport.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('NBC Sports', 'https://www.nbcsports.com/index.atom', 'https://nbcsports.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('PlanetF1', 'https://planetf1.com/rss', 'https://planetf1.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('portsmouth.co.uk', 'https://portsmouth.co.uk/rss', 'https://portsmouth.co.uk', 'sports', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('RaceFans', 'https://www.racefans.net/feed/', 'https://racefans.net', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('racingnews365.com', 'https://racingnews365.com/feed/news.xml', 'https://racingnews365.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Read Man Utd', 'https://readmanutd.com/feed/', 'https://readmanutd.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('RomaPress', 'https://romapress.net/feed', 'https://romapress.net', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Sports Illustrated', 'https://www.si.com/feed', 'https://si.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('supercarblondie.com', 'https://supercarblondie.com/feed/', 'https://supercarblondie.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Talk Chelsea', 'https://talkchelsea.net/feed', 'https://talkchelsea.net', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Caterer', 'https://thecaterer.com/feed/', 'https://thecaterer.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Liverpool Offside', 'https://liverpooloffside.sbnation.com/rss/index.xml', 'https://liverpooloffside.sbnation.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Race', 'https://www.the-race.com/rss/', 'https://the-race.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Stacey West', 'https://staceywest.net/feed/', 'https://staceywest.net', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('thestar.co.uk', 'https://thestar.co.uk/rss', 'https://thestar.co.uk', 'sports', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Y Clwb Pêl-droed', 'https://clwbpeldroed.org/feed/', 'https://clwbpeldroed.org', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Yorkshire Evening Post', 'https://yorkshireeveningpost.co.uk/rss', 'https://yorkshireeveningpost.co.uk', 'sports', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('24/7 Wall St.', 'https://247wallst.com/feed/', 'https://247wallst.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('9to5Toys', 'https://9to5toys.com/feed/', 'https://9to5toys.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('AIP Publishing LLC', 'https://publishing.aip.org/feed/', 'https://publishing.aip.org', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('AiThority', 'https://aithority.com/feed/', 'https://aithority.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Amateur Photographer', 'https://amateurphotographer.com/feed/', 'https://amateurphotographer.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Android Authority', 'https://www.androidauthority.com/feed/', 'https://androidauthority.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Android Headlines', 'https://androidheadlines.com/feed', 'https://androidheadlines.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Android Police', 'https://androidpolice.com/feed', 'https://androidpolice.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Appleosophy', 'https://appleosophy.com/feed/', 'https://appleosophy.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Auto Express', 'https://www.autoexpress.co.uk/rss', 'https://autoexpress.co.uk', 'tech', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('bgr.com', 'https://www.bgr.com/category/news/feed/', 'https://bgr.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('bloomingbit', 'https://en.bloomingbit.io/rss.xml', 'https://en.bloomingbit.io', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('BusinessLine', 'https://www.thehindubusinessline.com/feeder/default.rss', 'https://thehindubusinessline.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('CNET', 'https://www.cnet.com/rss/news/', 'https://cnet.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Computerworld', 'https://www.computerworld.com/feed/', 'https://computerworld.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Creative Bloq', 'https://www.creativebloq.com/feeds.xml', 'https://creativebloq.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Cult of Mac', 'https://www.cultofmac.com/feed/', 'https://cultofmac.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Digital Camera World', 'https://www.digitalcameraworld.com/feeds.xml', 'https://digitalcameraworld.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Digital Foundry', 'https://www.digitalfoundry.net/feed', 'https://digitalfoundry.net', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Digital Watch Observatory', 'https://dig.watch/feed', 'https://dig.watch', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('digitimes', 'https://www.digitimes.com/rss/daily.xml', 'https://digitimes.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('EasternEye', 'https://easterneye.biz/feeds/feed.rss', 'https://easterneye.biz', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('eciks.org', 'https://eciks.org/feed', 'https://eciks.org', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Fast Company', 'https://fastcompany.com/rss', 'https://fastcompany.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Fratello Watches', 'https://www.fratellowatches.com/feed', 'https://fratellowatches.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Geeky Gadgets', 'https://www.geeky-gadgets.com/feed/', 'https://geeky-gadgets.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('GSMArena.com', 'https://www.gsmarena.com/rss-news-reviews.php3', 'https://gsmarena.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Guido Fawkes', 'https://order-order.com/feed/', 'https://order-order.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('HotHardware', 'https://hothardware.com/rss', 'https://hothardware.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('IGN', 'https://www.ign.com/rss/v2/articles/feed', 'https://ign.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('igor´sLAB', 'https://www.igorslab.de/feed/', 'https://igorslab.de', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Innovation News Network', 'https://www.innovationnewsnetwork.com/feed/', 'https://innovationnewsnetwork.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Institut Montaigne', 'https://institutmontaigne.org/rss.xml', 'https://institutmontaigne.org', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Investor''s Business Daily', 'https://investors.com/feed', 'https://investors.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Invezz', 'https://invezz.com/feed/', 'https://invezz.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('japan-forward.com', 'https://japan-forward.com/feed', 'https://japan-forward.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Khaleej Times', 'https://www.khaleejtimes.com/api/v1/collections/top-section.rss', 'https://khaleejtimes.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('KitGuru', 'https://www.kitguru.net/feed/', 'https://kitguru.net', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Letem světem Applem', 'https://www.letemsvetemapplem.eu/feed/', 'https://letemsvetemapplem.eu', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Lifehacker', 'https://lifehacker.com/feed/rss', 'https://lifehacker.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('MacDailyNews', 'https://macdailynews.com/feed/', 'https://macdailynews.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Macworld', 'https://www.macworld.com/en-gb/feed', 'https://macworld.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('MakeUseOf', 'https://www.makeuseof.com/feed', 'https://makeuseof.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('MarketBeat', 'https://www.marketbeat.com/rss.ashx?type=headlines', 'https://marketbeat.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('McKinsey & Company', 'https://mckinsey.com/rss', 'https://mckinsey.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('MLQ.ai', 'https://mlq.ai/news/rss/', 'https://mlq.ai', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Network World', 'https://www.networkworld.com/feed/', 'https://networkworld.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Notebookcheck', 'https://www.notebookcheck.net/RSS-Feed-Notebook-Reviews.8156.0.html', 'https://notebookcheck.net', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('PCMag UK', 'https://uk.pcmag.com/feed.xml', 'https://uk.pcmag.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('PCWorld', 'https://www.pcworld.com/feed', 'https://pcworld.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('PetaPixel', 'https://petapixel.com/feed', 'https://petapixel.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Pocket-lint', 'https://www.pocket-lint.com/feed', 'https://pocket-lint.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Popular Science', 'https://www.popsci.com/feed/', 'https://popsci.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Pure Xbox', 'https://www.purexbox.com/feed', 'https://purexbox.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Push Square', 'https://www.pushsquare.com/feed', 'https://pushsquare.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Quantum Zeitgeist', 'https://quantumzeitgeist.com/feed/', 'https://quantumzeitgeist.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('RockstarINTEL', 'https://rockstarintel.com/feed', 'https://rockstarintel.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Semiconductor Engineering', 'https://semiengineering.com/feed/', 'https://semiengineering.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Share Talk', 'https://www.share-talk.com/feed/', 'https://share-talk.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Sivers Semiconductors', 'https://sivers-semiconductors.com/feed', 'https://sivers-semiconductors.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Sporting Life', 'https://www.sportinglife.com/feed', 'https://sportinglife.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('stuff.tv', 'https://www.stuff.tv/feed/', 'https://stuff.tv', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Supply Chain Dive', 'https://www.supplychaindive.com/feeds/news/', 'https://supplychaindive.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Sur in English', 'https://www.surinenglish.com/rss/2.0/?section=', 'https://surinenglish.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Swansea University', 'https://swansea.ac.uk/press-office/rss.xml', 'https://swansea.ac.uk', 'tech', 4, 'gb', '{"origin": "gn_census", "authority": 0.82, "verify": "unknown"}'),
  ('T3', 'https://www.t3.com/feeds.xml', 'https://t3.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('talkingtechandaudio.com', 'https://talkingtechandaudio.com/feed/', 'https://talkingtechandaudio.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Tech Xplore', 'https://techxplore.com/rss-feed/', 'https://techxplore.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('tech-insider.org', 'https://tech-insider.org/feed/', 'https://tech-insider.org', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Tech.eu', 'https://tech.eu/feed', 'https://tech.eu', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('TechPowerUp', 'https://techpowerup.com/rss/news', 'https://techpowerup.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('TechRepublic', 'https://www.techrepublic.com/feed/', 'https://techrepublic.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Gadgeteer', 'https://the-gadgeteer.com/feed/', 'https://the-gadgeteer.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Quantum Insider', 'https://thequantuminsider.com/feed/', 'https://thequantuminsider.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('the5krunner', 'https://the5krunner.com/feed/', 'https://the5krunner.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Tom''s Guide', 'https://www.tomsguide.com/feeds.xml', 'https://tomsguide.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('University of Waterloo', 'https://uwaterloo.ca/rss.xml', 'https://uwaterloo.ca', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Video Games Chronicle', 'https://www.videogameschronicle.com/feed', 'https://videogameschronicle.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Washington Examiner', 'https://www.washingtonexaminer.com/feed/', 'https://washingtonexaminer.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Wccftech', 'https://wccftech.com/feed', 'https://wccftech.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Wigan Today', 'https://www.wigantoday.net/rss', 'https://wigantoday.net', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "blocked"}'),
  ('Windows Central', 'https://www.windowscentral.com/feeds.xml', 'https://windowscentral.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Windows Latest', 'https://www.windowslatest.com/feed/', 'https://windowslatest.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('ABNA English', 'https://en.abna24.com/rss', 'https://en.abna24.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('arabnews.jp', 'https://www.arabnews.jp/feed/', 'https://arabnews.jp', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Argyll and Bute Council', 'https://argyll-bute.gov.uk/rss.xml', 'https://argyll-bute.gov.uk', 'world', 4, 'gb', '{"origin": "gn_census", "authority": 0.8, "verify": "unknown"}'),
  ('Asharq Al-Awsat English', 'https://english.aawsat.com/feed', 'https://english.aawsat.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Atlantic Council', 'https://www.atlanticcouncil.org/feed/', 'https://atlanticcouncil.org', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Boing Boing', 'https://boingboing.net/feed', 'https://boingboing.net', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Bored Panda', 'https://www.boredpanda.com/feed/', 'https://boredpanda.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Cape Coral Breeze', 'https://capecoralbreeze.com/feed', 'https://capecoralbreeze.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Center for European Policy Analysis (CEPA)', 'https://cepa.org/feed', 'https://cepa.org', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Crude Oil Prices Today | OilPrice.com', 'https://oilprice.com/rss.xml', 'https://oilprice.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Crypto Briefing', 'https://cryptobriefing.com/feed', 'https://cryptobriefing.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('DayakDaily', 'https://dayakdaily.com/feed/', 'https://dayakdaily.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Doctors Without Borders', 'https://doctorswithoutborders.org/rss.xml', 'https://doctorswithoutborders.org', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('EA WorldView', 'https://eaworldview.com/feed/', 'https://eaworldview.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Electoral Reform Society', 'https://electoral-reform.org.uk/feed/', 'https://electoral-reform.org.uk', 'world', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('EUobserver', 'https://euobserver.com/feed/', 'https://euobserver.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Euromaidan Press', 'https://euromaidanpress.com/feed/', 'https://euromaidanpress.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "blocked"}'),
  ('Euronews.com', 'https://www.euronews.com/rss', 'https://euronews.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('European Council on Foreign Relations', 'https://ecfr.eu/feed/', 'https://ecfr.eu', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Foundation for Defense of Democracies', 'https://fdd.org/feed/', 'https://fdd.org', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('GB News', 'https://www.gbnews.com/feeds/feed.rss', 'https://gbnews.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Genocide Watch', 'https://www.genocidewatch.com/blog-feed.xml', 'https://genocidewatch.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Gizmodo', 'https://gizmodo.com/feed', 'https://gizmodo.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Harvard Kennedy School', 'https://hks.harvard.edu/rss.xml', 'https://hks.harvard.edu', 'world', 4, null, '{"origin": "gn_census", "authority": 0.82, "verify": "unknown"}'),
  ('Houston Public Media', 'https://www.houstonpublicmedia.org/rsslatest.xml', 'https://houstonpublicmedia.org', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Human Rights Watch', 'https://hrw.org/rss', 'https://hrw.org', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Institute for Government', 'https://instituteforgovernment.org.uk/rss', 'https://instituteforgovernment.org.uk', 'world', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('IntelliNews', 'https://intellinews.com/feed/', 'https://intellinews.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Internazionale', 'https://www.internazionale.it/sitemaps/rss_italia.xml', 'https://internazionale.it', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('J Street', 'https://jstreet.org/feed', 'https://jstreet.org', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('KOHA.net', 'https://www.koha.net/rss', 'https://koha.net', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Kyiv Post', 'https://kyivpost.com/feed', 'https://kyivpost.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('LabourList', 'https://labourlist.org/feed', 'https://labourlist.org', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Latest news from Azerbaijan', 'https://news.az/rss.xml', 'https://news.az', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Le Monde.fr', 'https://www.lemonde.fr/en/rss/une.xml', 'https://lemonde.fr', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Long War Journal', 'https://www.longwarjournal.org/feed', 'https://longwarjournal.org', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Mashable', 'https://mashable.com/feeds/rss/all', 'https://mashable.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Meduza', 'https://meduza.io/rss/all', 'https://meduza.io', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Metro.co.uk', 'https://metro.co.uk/feed/', 'https://metro.co.uk', 'world', 3, 'gb', '{"origin": "gn_census", "authority": 0.64, "verify": "ok"}'),
  ('Middle East Eye', 'https://www.middleeasteye.net/rss', 'https://middleeasteye.net', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Middle East Monitor', 'https://www.middleeastmonitor.com/comments/feed/', 'https://middleeastmonitor.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('NBC News', 'https://nbcnews.com/feed', 'https://nbcnews.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Open Access Government', 'https://www.openaccessgovernment.org/feed/', 'https://openaccessgovernment.org', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('politico.eu', 'https://www.politico.eu/feed/', 'https://politico.eu', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('PYMNTS.com', 'https://www.pymnts.com/feed/', 'https://pymnts.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Real Instituto Elcano', 'https://www.realinstitutoelcano.org/feed/', 'https://realinstitutoelcano.org', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Refugees International', 'https://refugeesinternational.org/feed', 'https://refugeesinternational.org', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('SPICe Spotlight', 'https://spice-spotlight.scot/feed/', 'https://spice-spotlight.scot', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Straight Arrow', 'https://san.com/feed', 'https://san.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Sunflower State Journal', 'https://sunflowerstatejournal.com/feed/', 'https://sunflowerstatejournal.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('TechRadar', 'https://www.techradar.com/uk/feeds.xml', 'https://techradar.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('The i Paper', 'https://inews.co.uk/feed', 'https://inews.co.uk', 'world', 4, 'gb', '{"origin": "gn_census", "authority": 0.78, "verify": "ok"}'),
  ('The Kyiv Independent', 'https://kyivindependent.com/news-archive/rss/', 'https://kyivindependent.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Mirror', 'https://www.mirror.co.uk/rss.xml', 'https://mirror.co.uk', 'world', 3, 'gb', '{"origin": "gn_census", "authority": 0.62, "verify": "ok"}'),
  ('The Times of Israel', 'https://timesofisrael.com/feed/', 'https://timesofisrael.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('thecommonwealth.org', 'https://thecommonwealth.org/rss.xml', 'https://thecommonwealth.org', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('TradingView', 'https://tradingview.com/feed', 'https://tradingview.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Truthout', 'https://truthout.org/feed/?withoutcomments=1', 'https://truthout.org', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('UK Defence Journal', 'https://ukdefencejournal.org.uk/feed/', 'https://ukdefencejournal.org.uk', 'world', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Vanguard News', 'https://www.vanguardngr.com/feed/', 'https://vanguardngr.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Visual Capitalist', 'https://www.visualcapitalist.com/feed/', 'https://visualcapitalist.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Українська правда', 'https://pravda.com.ua/rss', 'https://pravda.com.ua', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Українські Національні Новини (УНН)', 'https://unn.ua/rss/news_uk.xml', 'https://unn.ua', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}')
on conflict (feed_url) do nothing;
