-- 0037_promote_gn_sources_full.sql
-- APPLIED-STATE NOTE (2026-07-12): prod already has 150 gn_census feeds live
--   (0036 batch = 54  +  a hand-curated ~96 high-confidence subset of the set below).
-- This file is the FULL 226-feed quality set. It is idempotent (ON CONFLICT DO NOTHING):
-- applying it simply ADDS the long-tail feeds (hyper-local + non-Latin-named outlets) that
-- were intentionally held back. Apply only if you want the full long tail.
--
-- Promotes QUALITY publishers discovered via the Google News census (Tom News, 2026-07-12)
-- to first-class RSS feeds so the Google-News hybrid fill can retire. Quality-filtered:
-- image-carrying + active, or authoritative. Every feed verified to parse. feed_url UNIQUE
-- + ON CONFLICT DO NOTHING → idempotent and safe to re-apply over the earlier 0036 batch.
-- 226 feeds (212 carry images natively → NewsFirst gets photos without decoding).
insert into public.sources (name, feed_url, home_url, category, weight, region, meta) values
  ('africanews.com', 'https://africanews.com/feed', 'https://africanews.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('AI Business', 'https://aibusiness.com/rss.xml', 'https://aibusiness.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Capitol News Illinois', 'https://capitolnewsillinois.com/feed/', 'https://capitolnewsillinois.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('City Journal', 'https://city-journal.org/rss.xml', 'https://city-journal.org', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Davis Vanguard', 'https://davisvanguard.org/feed/', 'https://davisvanguard.org', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Electronic Frontier Foundation', 'https://eff.org/rss.xml', 'https://eff.org', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Globes - Israel Business News', 'https://en.globes.co.il/WebService/Rss/RssFeeder.asmx/FeederNode?iID=942', 'https://en.globes.co.il', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('inc.com', 'https://inc.com/rss', 'https://inc.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('IT Pro', 'https://www.itpro.com/feeds.xml', 'https://itpro.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Luxembourg Times', 'https://luxtimes.lu/en/rss', 'https://luxtimes.lu', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('MyStateline', 'https://mystateline.com/feed', 'https://mystateline.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('qz.com', 'https://qz.com/feed', 'https://qz.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Reason Magazine', 'https://reason.com/feed/', 'https://reason.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('spyglass.org', 'https://spyglass.org/rss/', 'https://spyglass.org', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The National Law Review', 'https://natlawreview.com/feed', 'https://natlawreview.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('the-decoder.com', 'https://the-decoder.com/feed/', 'https://the-decoder.com', 'ai', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('airlive', 'https://airlive.net/feed/', 'https://airlive.net', 'business', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Devon Live', 'https://www.devonlive.com/rss.xml', 'https://devonlive.com', 'business', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Amnesty International', 'https://www.amnesty.org/en/feed/', 'https://amnesty.org', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Brighton & Hove City Council', 'https://brighton-hove.gov.uk/rss.xml', 'https://brighton-hove.gov.uk', 'climate', 4, 'gb', '{"origin": "gn_census", "authority": 0.8, "verify": "unknown"}'),
  ('Dailynewsegypt', 'https://www.dailynewsegypt.com/feed/', 'https://dailynewsegypt.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('East Devon District Council', 'https://news.eastdevon.gov.uk/rss', 'https://news.eastdevon.gov.uk', 'climate', 4, 'gb', '{"origin": "gn_census", "authority": 0.8, "verify": "unknown"}'),
  ('EV Powered', 'https://evpowered.co.uk/feed/', 'https://evpowered.co.uk', 'climate', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Global Government Forum', 'https://www.globalgovernmentforum.com/feed/', 'https://globalgovernmentforum.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('InsideEVs', 'https://insideevs.com/rss/news/all/', 'https://insideevs.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Interesting Engineering', 'https://interestingengineering.com/feed', 'https://interestingengineering.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Jalopnik', 'https://www.jalopnik.com/category/news/feed/', 'https://jalopnik.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('My Edmonds News', 'https://myedmondsnews.com/feed/', 'https://myedmondsnews.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Noema Magazine', 'https://www.noemamag.com/feed/', 'https://noemamag.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('OkDiario', 'https://okdiario.com/feed', 'https://okdiario.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Peterborough Telegraph', 'https://peterboroughtoday.co.uk/rss', 'https://peterboroughtoday.co.uk', 'climate', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Tehran Times', 'https://tehrantimes.com/rss', 'https://tehrantimes.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Diplomat – Asia-Pacific', 'https://thediplomat.com/feed', 'https://thediplomat.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Japan Times', 'https://japantimes.co.jp/feed/', 'https://japantimes.co.jp', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('theenergyst.com', 'https://theenergyst.com/feed/', 'https://theenergyst.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Time Magazine', 'https://time.com/feed', 'https://time.com', 'climate', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('University of Exeter News', 'https://news.exeter.ac.uk/feed/', 'https://news.exeter.ac.uk', 'climate', 4, 'gb', '{"origin": "gn_census", "authority": 0.82, "verify": "unknown"}'),
  ('BeInCrypto', 'https://beincrypto.com/feed', 'https://beincrypto.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Cointribune', 'https://www.cointribune.com/feed/', 'https://cointribune.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('CryptoPotato', 'https://cryptopotato.com/feed/', 'https://cryptopotato.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('CryptoSlate', 'https://cryptoslate.com/feed/', 'https://cryptoslate.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Deccan Herald', 'https://deccanherald.com/feed', 'https://deccanherald.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Diari ARA', 'https://en.ara.cat/rss/', 'https://en.ara.cat', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Investing News Network', 'https://investingnews.com/feed', 'https://investingnews.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('kuathletics.com', 'https://kuathletics.com/rss', 'https://kuathletics.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Mishcon de Reya LLP', 'https://mishcon.com/rss', 'https://mishcon.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Texas Tribune', 'https://www.texastribune.org/feed/', 'https://texastribune.org', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('صوت الإمارات', 'https://voiceofemirates.com/feed', 'https://voiceofemirates.com', 'crypto', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('93.3 The Drive', 'https://933thedrive.com/feed', 'https://933thedrive.com', 'economics', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Big Issue', 'https://www.bigissue.com/feed/', 'https://bigissue.com', 'economics', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Geographical', 'https://geographical.co.uk/feed', 'https://geographical.co.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Mortgage Soup', 'https://mortgagesoup.co.uk/feed/', 'https://mortgagesoup.co.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Mortgage Strategy', 'https://www.mortgagestrategy.co.uk/feed/', 'https://mortgagestrategy.co.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Critic', 'https://thecritic.co.uk/feed/', 'https://thecritic.co.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Thelead.uk', 'https://national.thelead.uk/feed', 'https://national.thelead.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('thenewworld.co.uk', 'https://thenewworld.co.uk/feed', 'https://thenewworld.co.uk', 'economics', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('YouGov', 'https://yougov.com/en/rss', 'https://yougov.com', 'economics', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('A.V. Club', 'https://www.avclub.com/rss.xml', 'https://avclub.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('ABC7 Los Angeles', 'https://abc7.com/feed/', 'https://abc7.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Bell of Lost Souls', 'https://www.belloflostsouls.net/feed', 'https://belloflostsouls.net', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Cosmopolitan', 'https://cosmopolitan.com/rss', 'https://cosmopolitan.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Discover SWNS', 'https://discover.swns.com/feed', 'https://discover.swns.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('E! News', 'https://eonline.com/feed', 'https://eonline.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('empireonline.com', 'https://rss.onebauer.media/api/feed-aggregator?hostname=https://www.empireonline.com', 'https://empireonline.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Far Out Magazine', 'https://faroutmagazine.co.uk/feed/', 'https://faroutmagazine.co.uk', 'entertainment', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "blocked"}'),
  ('Fox News', 'https://moxie.foxnews.com/google-publisher/latest.xml', 'https://foxnews.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('jezebel.com', 'https://www.jezebel.com/rss.xml', 'https://jezebel.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Louder', 'https://www.loudersound.com/feeds.xml', 'https://loudersound.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Marie Claire', 'https://www.marieclaire.com/feeds.xml', 'https://marieclaire.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('MovieWeb', 'https://movieweb.com/feed', 'https://movieweb.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('MusicRadar', 'https://www.musicradar.com/feeds.xml', 'https://musicradar.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('North Wales Live', 'https://www.dailypost.co.uk/rss.xml', 'https://dailypost.co.uk', 'entertainment', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Page Six', 'https://pagesix.com/feed/', 'https://pagesix.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('PureWow', 'https://www.purewow.com/rss/feed_national.xml', 'https://purewow.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Radio Times', 'https://www.radiotimes.com/feed', 'https://radiotimes.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('The Free Press', 'https://thefp.com/feed', 'https://thefp.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('upi.com', 'https://rss.upi.com/news/news.rss', 'https://upi.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Vogue', 'https://www.vogue.com/feed/rss', 'https://vogue.com', 'entertainment', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Cambridge News', 'https://www.cambridge-news.co.uk/rss.xml', 'https://cambridge-news.co.uk', 'health', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('CIDRAP', 'https://cidrap.umn.edu/rss.xml', 'https://cidrap.umn.edu', 'health', 4, null, '{"origin": "gn_census", "authority": 0.82, "verify": "unknown"}'),
  ('Community Pharmacy England', 'https://cpe.org.uk/feed/podcast', 'https://cpe.org.uk', 'health', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('GOV.UK blogs', 'https://educationhub.blog.gov.uk/feed/', 'https://educationhub.blog.gov.uk', 'health', 4, 'gb', '{"origin": "gn_census", "authority": 0.8, "verify": "unknown"}'),
  ('health-ni.gov.uk', 'https://health-ni.gov.uk/rss.xml', 'https://health-ni.gov.uk', 'health', 4, 'gb', '{"origin": "gn_census", "authority": 0.8, "verify": "unknown"}'),
  ('HSJ | Health Service Journal', 'https://www.hsj.co.uk/20703.rss', 'https://hsj.co.uk', 'health', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('KFF', 'https://www.kff.org/feed/', 'https://kff.org', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Leeds Live', 'https://www.leeds-live.co.uk/rss.xml', 'https://leeds-live.co.uk', 'health', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Medical Xpress', 'https://medicalxpress.com/rss-feed/', 'https://medicalxpress.com', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Newsroom | Weill Cornell Medicine', 'https://news.weill.cornell.edu/rss.xml', 'https://news.weill.cornell.edu', 'health', 4, null, '{"origin": "gn_census", "authority": 0.82, "verify": "unknown"}'),
  ('Oncodaily', 'https://oncodaily.com/feed', 'https://oncodaily.com', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Pharmacy Business', 'https://pharmacy.biz/feeds/feed.rss', 'https://pharmacy.biz', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Shropshire Council Newsroom', 'https://newsroom.shropshire.gov.uk/feed/', 'https://newsroom.shropshire.gov.uk', 'health', 4, 'gb', '{"origin": "gn_census", "authority": 0.8, "verify": "unknown"}'),
  ('Stock Titan', 'https://www.stocktitan.net/rss', 'https://stocktitan.net', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Bulwark', 'https://thebulwark.com/feed', 'https://thebulwark.com', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Hill', 'https://thehill.com/feed/', 'https://thehill.com', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Hindu', 'https://www.thehindu.com/feeder/default.rss', 'https://thehindu.com', 'health', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Sentinel', 'https://www.stokesentinel.co.uk/rss.xml', 'https://stokesentinel.co.uk', 'health', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The University of Manchester', 'https://manchester.ac.uk/rss', 'https://manchester.ac.uk', 'health', 4, 'gb', '{"origin": "gn_census", "authority": 0.82, "verify": "unknown"}'),
  ('University of Cambridge', 'https://cam.ac.uk/feed', 'https://cam.ac.uk', 'health', 4, 'gb', '{"origin": "gn_census", "authority": 0.82, "verify": "unknown"}'),
  ('University of Liverpool', 'https://news.liverpool.ac.uk/feed/', 'https://news.liverpool.ac.uk', 'health', 4, 'gb', '{"origin": "gn_census", "authority": 0.82, "verify": "unknown"}'),
  ('Wakefield Express', 'https://wakefieldexpress.co.uk/rss', 'https://wakefieldexpress.co.uk', 'health', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Centro Nacional de Investigaciones Oncológicas - CNIO', 'https://www.cnio.es/feed/', 'https://cnio.es', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('CPG Click Oil and Gas', 'https://en.clickpetroleoegas.com.br/feed', 'https://en.clickpetroleoegas.com.br', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Futurism', 'https://futurism.com/feed', 'https://futurism.com', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Genetic Literacy Project', 'https://geneticliteracyproject.org/feed', 'https://geneticliteracyproject.org', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('News-Medical', 'https://www.news-medical.net/syndication.axd?format=rss', 'https://news-medical.net', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Press and Journal', 'https://www.pressandjournal.co.uk/feed', 'https://pressandjournal.co.uk', 'science', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('SingularityHub', 'https://singularityhub.com/feed/', 'https://singularityhub.com', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The University of Utah', 'https://attheu.utah.edu/feed/', 'https://attheu.utah.edu', 'science', 4, null, '{"origin": "gn_census", "authority": 0.82, "verify": "unknown"}'),
  ('UIC today', 'https://today.uic.edu/feed', 'https://today.uic.edu', 'science', 4, null, '{"origin": "gn_census", "authority": 0.82, "verify": "unknown"}'),
  ('www.heart.org', 'https://newsroom.heart.org/rss.xml', 'https://newsroom.heart.org', 'science', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Carnegie Science', 'https://carnegiescience.edu/rss.xml', 'https://carnegiescience.edu', 'space', 4, null, '{"origin": "gn_census", "authority": 0.82, "verify": "unknown"}'),
  ('Futura, le média qui explore le monde', 'https://www.futura-sciences.com/rss/actualites.xml', 'https://futura-sciences.com', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('La Brújula Verde', 'https://www.labrujulaverde.com/feed', 'https://labrujulaverde.com', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('National Air and Space Museum', 'https://airandspace.si.edu/rss.xml', 'https://airandspace.si.edu', 'space', 4, null, '{"origin": "gn_census", "authority": 0.82, "verify": "unknown"}'),
  ('Nautilus | Science', 'https://nautil.us/feed', 'https://nautil.us', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Pandaily', 'https://pandaily.com/feed', 'https://pandaily.com', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Report.az', 'https://report.az/rss', 'https://report.az', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Tech Explorist', 'https://www.techexplorist.com/feed/', 'https://techexplorist.com', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('University of St Andrews', 'https://news.st-andrews.ac.uk/feed/', 'https://news.st-andrews.ac.uk', 'space', 4, 'gb', '{"origin": "gn_census", "authority": 0.82, "verify": "unknown"}'),
  ('ValleyCentral.com', 'https://valleycentral.com/feed', 'https://valleycentral.com', 'space', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Chronicle Live', 'https://www.chroniclelive.co.uk/rss.xml', 'https://chroniclelive.co.uk', 'sports', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Crash.net', 'https://www.crash.net/rss', 'https://crash.net', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Daily Star', 'https://www.dailystar.co.uk/rss.xml', 'https://dailystar.co.uk', 'sports', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Derbyshire Live', 'https://www.derbytelegraph.co.uk/rss.xml', 'https://derbytelegraph.co.uk', 'sports', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Football365', 'https://football365.com/rss', 'https://football365.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Footy Headlines', 'https://www.footyheadlines.com/atom.xml', 'https://footyheadlines.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('FotMob', 'https://www.fotmob.com/topnews/feed?format=atom', 'https://fotmob.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('FourFourTwo', 'https://www.fourfourtwo.com/feeds.xml', 'https://fourfourtwo.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('GlasgowWorld', 'https://glasgowworld.com/rss', 'https://glasgowworld.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('GPblog', 'https://www.gpblog.com/en/sitemap/news.xml', 'https://gpblog.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('grandprix247', 'https://www.grandprix247.com/sitemap/news.xml', 'https://grandprix247.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('House & Garden', 'https://www.houseandgarden.co.uk/feed/rss', 'https://houseandgarden.co.uk', 'sports', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Hull Live', 'https://www.hulldailymail.co.uk/rss.xml', 'https://hulldailymail.co.uk', 'sports', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('PlanetF1', 'https://planetf1.com/rss', 'https://planetf1.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('portsmouth.co.uk', 'https://portsmouth.co.uk/rss', 'https://portsmouth.co.uk', 'sports', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Read Man Utd', 'https://readmanutd.com/feed/', 'https://readmanutd.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Sports Illustrated', 'https://www.si.com/feed', 'https://si.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('supercarblondie.com', 'https://supercarblondie.com/feed/', 'https://supercarblondie.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Talk Chelsea', 'https://talkchelsea.net/feed', 'https://talkchelsea.net', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Race', 'https://www.the-race.com/rss/', 'https://the-race.com', 'sports', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('thestar.co.uk', 'https://thestar.co.uk/rss', 'https://thestar.co.uk', 'sports', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Yorkshire Evening Post', 'https://yorkshireeveningpost.co.uk/rss', 'https://yorkshireeveningpost.co.uk', 'sports', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('24/7 Wall St.', 'https://247wallst.com/feed/', 'https://247wallst.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Amateur Photographer', 'https://amateurphotographer.com/feed/', 'https://amateurphotographer.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Android Authority', 'https://www.androidauthority.com/feed/', 'https://androidauthority.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Android Headlines', 'https://androidheadlines.com/feed', 'https://androidheadlines.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Android Police', 'https://androidpolice.com/feed', 'https://androidpolice.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Appleosophy', 'https://appleosophy.com/feed/', 'https://appleosophy.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Auto Express', 'https://www.autoexpress.co.uk/rss', 'https://autoexpress.co.uk', 'tech', 3, 'gb', '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('bgr.com', 'https://www.bgr.com/category/news/feed/', 'https://bgr.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('BusinessLine', 'https://www.thehindubusinessline.com/feeder/default.rss', 'https://thehindubusinessline.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('CNET', 'https://www.cnet.com/rss/news/', 'https://cnet.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Computerworld', 'https://www.computerworld.com/feed/', 'https://computerworld.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Creative Bloq', 'https://www.creativebloq.com/feeds.xml', 'https://creativebloq.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Cult of Mac', 'https://www.cultofmac.com/feed/', 'https://cultofmac.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Digital Camera World', 'https://www.digitalcameraworld.com/feeds.xml', 'https://digitalcameraworld.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Digital Foundry', 'https://www.digitalfoundry.net/feed', 'https://digitalfoundry.net', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('digitimes', 'https://www.digitimes.com/rss/daily.xml', 'https://digitimes.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('EasternEye', 'https://easterneye.biz/feeds/feed.rss', 'https://easterneye.biz', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('eciks.org', 'https://eciks.org/feed', 'https://eciks.org', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Fast Company', 'https://fastcompany.com/rss', 'https://fastcompany.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('HotHardware', 'https://hothardware.com/rss', 'https://hothardware.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('IGN', 'https://www.ign.com/rss/v2/articles/feed', 'https://ign.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('igor´sLAB', 'https://www.igorslab.de/feed/', 'https://igorslab.de', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Invezz', 'https://invezz.com/feed/', 'https://invezz.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Khaleej Times', 'https://www.khaleejtimes.com/api/v1/collections/top-section.rss', 'https://khaleejtimes.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Letem světem Applem', 'https://www.letemsvetemapplem.eu/feed/', 'https://letemsvetemapplem.eu', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Lifehacker', 'https://lifehacker.com/feed/rss', 'https://lifehacker.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Macworld', 'https://www.macworld.com/en-gb/feed', 'https://macworld.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('MakeUseOf', 'https://www.makeuseof.com/feed', 'https://makeuseof.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Network World', 'https://www.networkworld.com/feed/', 'https://networkworld.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Notebookcheck', 'https://www.notebookcheck.net/RSS-Feed-Notebook-Reviews.8156.0.html', 'https://notebookcheck.net', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('PCMag UK', 'https://uk.pcmag.com/feed.xml', 'https://uk.pcmag.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('PCWorld', 'https://www.pcworld.com/feed', 'https://pcworld.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Pocket-lint', 'https://www.pocket-lint.com/feed', 'https://pocket-lint.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Popular Science', 'https://www.popsci.com/feed/', 'https://popsci.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Pure Xbox', 'https://www.purexbox.com/feed', 'https://purexbox.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Push Square', 'https://www.pushsquare.com/feed', 'https://pushsquare.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Quantum Zeitgeist', 'https://quantumzeitgeist.com/feed/', 'https://quantumzeitgeist.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('stuff.tv', 'https://www.stuff.tv/feed/', 'https://stuff.tv', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Sur in English', 'https://www.surinenglish.com/rss/2.0/?section=', 'https://surinenglish.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Swansea University', 'https://swansea.ac.uk/press-office/rss.xml', 'https://swansea.ac.uk', 'tech', 4, 'gb', '{"origin": "gn_census", "authority": 0.82, "verify": "unknown"}'),
  ('T3', 'https://www.t3.com/feeds.xml', 'https://t3.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Tech Xplore', 'https://techxplore.com/rss-feed/', 'https://techxplore.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Tech.eu', 'https://tech.eu/feed', 'https://tech.eu', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('TechPowerUp', 'https://techpowerup.com/rss/news', 'https://techpowerup.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Gadgeteer', 'https://the-gadgeteer.com/feed/', 'https://the-gadgeteer.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Quantum Insider', 'https://thequantuminsider.com/feed/', 'https://thequantuminsider.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('the5krunner', 'https://the5krunner.com/feed/', 'https://the5krunner.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Tom''s Guide', 'https://www.tomsguide.com/feeds.xml', 'https://tomsguide.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Washington Examiner', 'https://www.washingtonexaminer.com/feed/', 'https://washingtonexaminer.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Wccftech', 'https://wccftech.com/feed', 'https://wccftech.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Wigan Today', 'https://www.wigantoday.net/rss', 'https://wigantoday.net', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "blocked"}'),
  ('Windows Central', 'https://www.windowscentral.com/feeds.xml', 'https://windowscentral.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Windows Latest', 'https://www.windowslatest.com/feed/', 'https://windowslatest.com', 'tech', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('ABNA English', 'https://en.abna24.com/rss', 'https://en.abna24.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Argyll and Bute Council', 'https://argyll-bute.gov.uk/rss.xml', 'https://argyll-bute.gov.uk', 'world', 4, 'gb', '{"origin": "gn_census", "authority": 0.8, "verify": "unknown"}'),
  ('Asharq Al-Awsat English', 'https://english.aawsat.com/feed', 'https://english.aawsat.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Boing Boing', 'https://boingboing.net/feed', 'https://boingboing.net', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Bored Panda', 'https://www.boredpanda.com/feed/', 'https://boredpanda.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Crypto Briefing', 'https://cryptobriefing.com/feed', 'https://cryptobriefing.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('EUobserver', 'https://euobserver.com/feed/', 'https://euobserver.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Euromaidan Press', 'https://euromaidanpress.com/feed/', 'https://euromaidanpress.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "blocked"}'),
  ('European Council on Foreign Relations', 'https://ecfr.eu/feed/', 'https://ecfr.eu', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Foundation for Defense of Democracies', 'https://fdd.org/feed/', 'https://fdd.org', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('GB News', 'https://www.gbnews.com/feeds/feed.rss', 'https://gbnews.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Genocide Watch', 'https://www.genocidewatch.com/blog-feed.xml', 'https://genocidewatch.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Gizmodo', 'https://gizmodo.com/feed', 'https://gizmodo.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Harvard Kennedy School', 'https://hks.harvard.edu/rss.xml', 'https://hks.harvard.edu', 'world', 4, null, '{"origin": "gn_census", "authority": 0.82, "verify": "unknown"}'),
  ('KOHA.net', 'https://www.koha.net/rss', 'https://koha.net', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Kyiv Post', 'https://kyivpost.com/feed', 'https://kyivpost.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Latest news from Azerbaijan', 'https://news.az/rss.xml', 'https://news.az', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Le Monde.fr', 'https://www.lemonde.fr/en/rss/une.xml', 'https://lemonde.fr', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Mashable', 'https://mashable.com/feeds/rss/all', 'https://mashable.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Meduza', 'https://meduza.io/rss/all', 'https://meduza.io', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('NBC News', 'https://nbcnews.com/feed', 'https://nbcnews.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('PYMNTS.com', 'https://www.pymnts.com/feed/', 'https://pymnts.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Straight Arrow', 'https://san.com/feed', 'https://san.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('TechRadar', 'https://www.techradar.com/uk/feeds.xml', 'https://techradar.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('The i Paper', 'https://inews.co.uk/feed', 'https://inews.co.uk', 'world', 4, 'gb', '{"origin": "gn_census", "authority": 0.78, "verify": "ok"}'),
  ('The Kyiv Independent', 'https://kyivindependent.com/news-archive/rss/', 'https://kyivindependent.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('The Mirror', 'https://www.mirror.co.uk/rss.xml', 'https://mirror.co.uk', 'world', 3, 'gb', '{"origin": "gn_census", "authority": 0.62, "verify": "ok"}'),
  ('Truthout', 'https://truthout.org/feed/?withoutcomments=1', 'https://truthout.org', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Visual Capitalist', 'https://www.visualcapitalist.com/feed/', 'https://visualcapitalist.com', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "ok"}'),
  ('Українська правда', 'https://pravda.com.ua/rss', 'https://pravda.com.ua', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}'),
  ('Українські Національні Новини (УНН)', 'https://unn.ua/rss/news_uk.xml', 'https://unn.ua', 'world', 3, null, '{"origin": "gn_census", "authority": 0.55, "verify": "unknown"}')
on conflict (feed_url) do nothing;
update public.sources set poll_interval_s = 1200 where meta->>'origin' = 'gn_census';
